sudo: required

language: python

services:
  - docker

before_install:
  - docker build -t superphy/docker-flask-conda:webserver .
  - docker run -d -p 127.0.0.1:80:4567 superphy/docker-flask-conda:webserver
  - docker ps -a

install:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - echo $TAG
  - echo $TRAVIS_BRANCH
  - docker push superphy/docker-flask-conda:$TRAVIS_BRANCH

script:
  - docker ps

notifications:
  email: false
