sudo: required

language: python

services:
  - docker

before_install:
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - echo $TAG
  - echo $TRAVIS_BRANCH

install:
  - docker build -t superphy/docker-flask-conda:$TAG .

script:
  - docker run -d -p 127.0.0.1:80:4567 superphy/docker-flask-conda:$TAG
  - docker ps -a

deploy:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push superphy/docker-flask-conda:$TAG


after_failure::
  - conda env list
  - pip list
  - conda env list | grep ssl
  - pip list | grep ssl
  - pip list | grep uwsgi

notifications:
  email: false
